ALTER TABLE matches
    ADD COLUMN format VARCHAR(32) NOT NULL DEFAULT 'BEST_OF_3_SETS';

ALTER TABLE matches
    ADD CONSTRAINT ck_matches_format CHECK (format IN ('BEST_OF_3_SETS', 'TWO_SETS_SUPER_TIEBREAK'));
